Ability to cancel a scenariorun-PROD-8693
Cosmo-Tech/cosmotech-api pull request #204
Opened 2022-01-28 14:51 UTC by mahkoCosmo

2022-01-31 08:55 UTC, vcarluer commented
Top feature :D I mage some review on naming and code factorization

2022-01-31 08:55 UTC, vcarluer requested changes

2022-01-31 08:55 UTC, vcarluer commented on scenariorun/src/main/openapi/scenariorun.yaml
> +  /organizations/{organization_id}/scenarioruns/{scenariorun_id}/workflows/{workflow_name}/stop:
You don't need to set workflow_name in path, it is stored in the scenariorun definition:
/organizations/{organization_id}/workspaces/{workspace_id}/scenarioruns/{scenariorun_id}/stop

2022-01-31 08:55 UTC, vcarluer commented on scenariorun/src/main/openapi/scenariorun.yaml
> +      operationId: stopScenario
I may have call it stopScenarioRun

2022-01-31 08:55 UTC, vcarluer commented on scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
> +  override fun stopScenario(
I may have call it stopScenarioRun

2022-01-31 08:55 UTC, vcarluer commented on scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
> +      workflowName: kotlin.String
not needed, workflowName in ScenarioRun info

2022-01-31 08:55 UTC, vcarluer commented on scenariorun/src/main/kotlin/com/cosmotech/scenariorun/azure/ScenarioRunServiceImpl.kt
> +    return workflowService.stopWorkflow(organizationId, scenariorunId, workflowName)
So here you need to fetch workflowName from scenariorunId prior to the call

2022-01-31 08:55 UTC, vcarluer commented on scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowService.kt
> +    return ScenarioRunStatus(
There is already a function which do this mapping "workflow status" => scenarioRunStatus : getScenarioRunStatus
Refactor both to have only one mapping function if possible.

2022-02-07 10:26 UTC, jreynard-code requested changes
Same remarks as @vcarluer.
GG ;)

2022-02-25 11:28 UTC, vcarluer approved these changes

2022-02-25 11:28 UTC, vcarluer commented on scenariorun/src/main/kotlin/com/cosmotech/scenariorun/workflow/argo/ArgoWorkflowService.kt
> +              .workflowServiceStopWorkflow(
Seems it is not taken into account since there is an issue in the Argo Workflow we use.

2022-02-25 11:29 UTC, merged