Add cache module structure
Cosmo-Tech/cosmotech-api pull request #390
Opened 2022-11-10 14:14 UTC by jreynard-code

Add cache module structure
Add 3 endpoints sample in cache module

2022-11-10 15:24 UTC, vcarluer requested changes
twincache module => twingraph module
cache => graph in code

2022-11-10 15:24 UTC, vcarluer commented on twincache/src/main/openapi/twincache.yaml
> +                type: string
Needs to have a response data structure here:

importRequestId (at least)
+ add an endpoint to get importStatus from importRequestId

2022-11-10 15:24 UTC, vcarluer commented on twincache/src/main/openapi/twincache.yaml
> +      description: Launch a mass import job
Needs to have a Body data structure here:

graphInstanceId
storageSource (need to groom if it is possible to have an agnostic source here without Azure adherence)

2022-11-10 15:24 UTC, vcarluer commented on twincache/src/main/openapi/twincache.yaml
> +      description: Run a query on cache
Needs to have a body data structure here:

* graphInstanceId
* graphInstanceVersion (can be latest, by default)
* cypherQuery

2022-11-10 15:24 UTC, vcarluer commented on twincache/src/main/openapi/twincache.yaml
> +        '200':
204

2022-11-10 15:24 UTC, vcarluer commented on twincache/src/main/openapi/twincache.yaml
> +        '200':
202

2022-11-15 14:52 UTC, icreated approved these changes
Ok

2022-11-15 14:58 UTC, merged