Twingraph implementation
Cosmo-Tech/cosmotech-api pull request #392
Opened 2022-11-16 15:46 UTC by icreated

2022-11-17 08:49 UTC, vcarluer requested changes
some changes

2022-11-17 08:49 UTC, vcarluer commented on build.gradle.kts
> +    implementation("com.redislabs:jredisgraph:2.6.0-rc3")
Maybe avoid rc release?

2022-11-17 08:49 UTC, vcarluer commented on api/src/main/resources/application.yml
> +twin-graph:
move to csm.platform

2022-11-17 08:49 UTC, vcarluer commented on twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphConfig.kt
> +@ConfigurationProperties(prefix = "twin-graph")
csm.platform.

2022-11-17 08:49 UTC, vcarluer commented on twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImpl.kt
> +      if (value is Node) {
And relationships?

2022-11-18 16:08 UTC, vcarluer commented on twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImpl.kt
> +    val redisGraphId = "${twinGraphQuery.graphId}:${twinGraphQuery.version}"
Make twinGraphQuery.version optional with default value = latest (fetch latest version from metadata)

2022-11-21 16:13 UTC, jreynard-code requested changes
LGTM, just few little remarks ;)

2022-11-21 16:13 UTC, jreynard-code commented on twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImpl.kt
> +    }
Handle case if lastVersion is not found or null. 
You can throw an exception (e.g. IllegalStateException)

2022-11-21 16:13 UTC, jreynard-code commented on twingraph/src/main/kotlin/com/cosmotech/twingraph/api/TwingraphServiceImpl.kt
> +    @Suppress("SpreadOperator") val count = jedis.del(*matchingKeys.toTypedArray())
Could you please find a way to remove the `@Suppress("SpreadOperator")` ?

2022-11-22 08:39 UTC, merged