New service scenariorunresults
Cosmo-Tech/cosmotech-api pull request #505
Opened 2023-05-31 09:46 UTC by Leopold-Cramer

2023-06-20 08:11 UTC, jreynard-code requested changes
LGTM :smile: 
Just some remarks ;)

2023-06-20 08:11 UTC, jreynard-code commented on scenariorunresult/src/main/openapi/scenariorunresult.yaml
> +            value1: value
Maybe add more realistic data

2023-09-07 10:12 UTC, jreynard-code requested changes
Just some remarks

2023-09-08 15:13 UTC, lalepee commented
![image](https://github.com/Cosmo-Tech/cosmotech-api/assets/94050519/5bb786b1-04bd-4289-992c-5034d0c4c60c)

2023-09-14 09:06 UTC, jreynard-code approved these changes
LGTM

2023-09-15 14:26 UTC, merged