Lcra/update acl organization workspace scenario
Cosmo-Tech/cosmotech-api pull request #555
Opened 2023-09-06 13:23 UTC by Leopold-Cramer

2023-09-19 10:07 UTC, lalepee requested changes

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                  assertThrows<CsmAccessForbiddenException> {
message validation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAuthenticatedRoles(any()) } returns listOf(role)
remove

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAccountIdentifier(any()) } returns FAKE_MAIL
move under workspace creation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                        mockOrganization(id = "id", roleName = FAKE_MAIL))
role

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                        mockOrganization(id = "id", roleName = FAKE_MAIL))
role

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAuthenticatedRoles(any()) } returns listOf(role)
remove

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAccountIdentifier(any()) } returns FAKE_MAIL
move under workspace creation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                  assertThrows<CsmAccessForbiddenException> {
message validation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                        mockOrganization(id = "id", roleName = FAKE_MAIL))
role

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAuthenticatedRoles(any()) } returns listOf(role)
remove

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAccountIdentifier(any()) } returns FAKE_MAIL
move under workspace creation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                  assertThrows<CsmAccessForbiddenException> {
message validation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAuthenticatedRoles(any()) } returns listOf(role)
remove

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAccountIdentifier(any()) } returns FAKE_MAIL
move under workspace creation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                  assertThrows<CsmAccessForbiddenException> {
message validation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                        mockOrganization(id = "id", roleName = FAKE_MAIL))
role

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAuthenticatedRoles(any()) } returns listOf(role)
remove

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                  assertThrows<CsmAccessForbiddenException> {
message validation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                        mockOrganization(id = "id", roleName = FAKE_MAIL))
role

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAuthenticatedRoles(any()) } returns listOf(role)
remove

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAccountIdentifier(any()) } returns FAKE_MAIL
move under workspace creation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                  assertThrows<CsmAccessForbiddenException> {
message validation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                        mockOrganization(id = "id", roleName = FAKE_MAIL))
role

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAuthenticatedRoles(any()) } returns listOf(role)
remove

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                every { getCurrentAccountIdentifier(any()) } returns FAKE_MAIL
move under workspace creation

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                        mockOrganization(id = "id", roleName = FAKE_MAIL))
role

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
> +                assertDoesNotThrow {
add **assertThrows** and validation on exception message

2023-09-19 10:07 UTC, lalepee commented on workspace/src/integrationTest/kotlin/com/cosmotech/worskpace/service/WorkspaceServiceIntegrationTest.kt
>        roleName: String = CONNECTED_ADMIN_USER,
replace roleName with userName

2023-10-06 14:54 UTC, lalepee approved these changes

2023-10-06 14:54 UTC, lalepee commented on dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceRBACTest.kt
> +package com.cosmotech.dataset.service
what is this ?

2023-10-06 14:54 UTC, lalepee commented on gradle.properties
> -useLocalLicenseAllowedFile=false
are you sure about that ?

2023-10-09 09:14 UTC, Leopold-Cramer commented on gradle.properties
> -useLocalLicenseAllowedFile=false
YES

2023-10-09 09:15 UTC, Leopold-Cramer commented on dataset/src/integrationTest/kotlin/com/cosmotech/dataset/service/DatasetServiceRBACTest.kt
> +package com.cosmotech.dataset.service
A mistake

2023-10-09 09:43 UTC, merged