Run results postgres controls (create / send / delete)
Cosmo-Tech/cosmotech-api pull request #687
Opened 2024-04-19 12:37 UTC by neomatamune

- Create DB on Run Start [PROD-13251]
- Delete DB when Run is deleted [PROD-13253]
- Create table and send data on /results/send calls [PROD-13246]
  - When data is empty fails
  - When data has new columns alters table to take new columns into account
  - Separate data into first level columns with type inference
    - boolean -> BOOLEAN
    - int / float -> NUMERICAL
    - string -> TEXT
    - Anything else -> JSONB
  - When column has incompatible types during the first call store column as JSONB data
  - When column has incompatible types on following calls fails
- Update rights for each system user as required 
  - reader : `CONNECT` on DB + `SELECT` on Tables
  - writer : `CONNECT` on DB + `CREATE` on Schema `public`

2024-04-19 15:03 UTC, sjoubert requested changes

2024-04-22 07:39 UTC, neomatamune commented on run/src/main/kotlin/com/cosmotech/run/exceptions/RunExceptionHandling.kt
> +    response.title = "Bad SQL Request"
Just some copy paste I forgot to rename, will change it

2024-04-22 07:43 UTC, neomatamune commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> +            .prepareStatement("GRANT SELECT ON TABLE \"$dataTableName\" TO $readerStorageUsername ")
It was in an effort to try to reduce at maximum the rights given to the reader

2024-04-22 07:44 UTC, neomatamune commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> +      throw e
can a `finally` be called even after a `throw` ?

2024-04-22 07:44 UTC, neomatamune commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> +    connection.close()
same as above : can a `finally` be called even after a `throw` ?

2024-04-22 07:46 UTC, neomatamune commented on run/src/main/kotlin/com/cosmotech/run/config/RunStorageConfig.kt
> +  fun writerRunStorageTemplate(
no idea, copied the `@Bean` from other definition you made, never looked at what it does, so tell me, what does it do ? is it important or I could just remove it and never think about it again ?

2024-04-22 08:25 UTC, jreynard-code commented on run/src/main/kotlin/com/cosmotech/run/config/RunStorageConfig.kt
> +  fun writerRunStorageTemplate(
Both can be removed as they are not used. Only adminuser should be kept I think. As we create a jdbc connection at runtime directly with username/password

2024-04-22 08:45 UTC, sjoubert commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> +            .prepareStatement("GRANT SELECT ON TABLE \"$dataTableName\" TO $readerStorageUsername ")
Ok, I have no real points to do that another way.

2024-04-22 11:42 UTC, jreynard-code commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> +      throw e
Yep.
Here is a little snippet:

```
fun main() {
    println("Start")

    try {
        throwException()
    } catch (e:IllegalStateException) {
        println("catch the error")
        throw e
    } finally {
        println("finally")
    }
}

fun throwException() {
    throw IllegalStateException("error")
}
```

Output is :
```
Start
catch the error
finally
```

2024-04-22 11:42 UTC, jreynard-code commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> +    connection.close()
yep same remark as above

2024-04-23 09:58 UTC, sjoubert approved these changes

2024-04-23 10:00 UTC, merged