add tests for run query endpoint
Cosmo-Tech/cosmotech-api pull request #694
Opened 2024-04-26 13:35 UTC by Leopold-Cramer

2024-04-26 13:58 UTC, sjoubert requested changes

2024-04-26 13:58 UTC, sjoubert commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> -            "jdbc:postgresql://$host:$port/$runId", readerStorageUsername, readerStoragePassword)
Do we go back to hardcode `localhost`, I don't think this is was we want (wrong merge conflict resolve on your part?)

2024-04-26 13:58 UTC, sjoubert commented on run/src/main/kotlin/com/cosmotech/run/service/RunServiceImpl.kt
> -    val run = getRun(organizationId, workspaceId, runnerId, runId)
If this is really not necessary then just remove the code, don't comment it. But I somehow doubt we want to remove RBAC checks. (Although maybe this is done elsewhere now).

Same a few lines below for another `getRun`

2024-04-26 13:58 UTC, sjoubert commented on run/src/main/openapi/run.yaml
> -            additionalProperties: true
I'm not sure how an `additionalProperties` to false behave when no specific properties are defined. Is it ok or does it prevent any content (which is probably not what we want)?

2024-04-30 09:44 UTC, jreynard-code approved these changes
LGTM

2024-05-06 15:15 UTC, merged