Remove state, lastRun, parentLastRun, rootLastRun on Runner + add lastRunId instead
Cosmo-Tech/cosmotech-api pull request #715
Opened 2024-05-30 10:00 UTC by jreynard-code

2024-05-30 11:52 UTC, lalepee requested changes

2024-05-30 11:52 UTC, lalepee commented on runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
> +    if (!runner.lastRunId.isNullOrBlank()) {
Can this be moved to a runnerInstance Function instead ?

2024-05-30 13:38 UTC, lalepee requested changes
Sorry some change needed again

2024-05-30 13:38 UTC, lalepee commented on runner/src/main/kotlin/com/cosmotech/runner/service/RunnerService.kt
> +    fun delete() {
The delete should be in the runnerService class. runnerService Class do action on runnerInstance Class. runnerInstance should only provide status.

2024-05-30 13:38 UTC, lalepee commented on runner/src/main/kotlin/com/cosmotech/runner/service/RunnerApiServiceImpl.kt
>      val runner = runnerService.getInstance(runnerId).userHasPermission(PERMISSION_DELETE)
var runner should be named runnerInstance

2024-05-31 10:01 UTC, neomatamune approved these changes

2024-05-31 10:03 UTC, merged